name: Example Workflow with Max Retry

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run job with retry logic
        run: |
          max_attempts=2
          attempt=0
          until [ $attempt -ge $max_attempts ]
          do
            attempt=$((attempt+1))
            echo "Attempt $attempt..."
            ./your_script.sh && break || echo "Attempt $attempt failed."
            if [ $attempt -ge $max_attempts ]; then
              echo "Job failed after $attempt attempts."
              exit 1
            fi
          done
