name: Example Workflow with Max Retry

on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        retry: [1]
    steps:
      - uses: actions/checkout@v3
      - name: Run my command
        run: |
          if [[ "${{ runner.retry_count }}" -eq 0 ]]; then
            # Command that might fail
            my_command
          fi
