name: Example Workflow with Max Retry

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run job with retry logic
        id: myStepId1
        continue-on-error: true
        run: |
          set -e
          set -x 
          hostname
      - name: Some action that can fail
        id: myStepId2
        if: steps.myStepId1.outcome == 'failure'
        continue-on-error: true
        run: |
          set -e
          set -x 
          hostname
        
