name: Example Workflow with Max Retry

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        retry: [1, 2]
    steps:
      - uses: actions/checkout@v3
      - name: Run my command
        run: |
          hostname
          if [[ $? -eq 0 ]]; then
            echo "Command succeeded on first attempt"
            exit 0
          fi
