name: Example Workflow with Max Retry

on: [push]
jobs:
  retry_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run task that fails first, succeeds second
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            if [[ "$GITHUB_RUN_ATTEMPT" == "1" ]]; then
              echo "This is the first attempt. Failing intentionally."
              exit 1
            else
              echo "This is attempt number $GITHUB_RUN_ATTEMPT. Succeeding."
              exit 0
            fi
      
      - name: Run if previous step succeeded
        if: success()
        run: echo "The task succeeded!"
      
      - name: Run if all attempts failed
        if: failure()
        run: echo "The task failed after all retry attempts"
