name: Example Workflow with Max Retry

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run job with retry logic
        uses: nick-fields/retry@v1
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 5
          command: |
             set -e
             set -x
             hostname
