name: Example Workflow with Max Retry

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        retry: [1, 2]
    steps:
      - uses: actions/checkout@v3
      - name: Build Application
        run: |
          # Build commands here
      - name: Deploy Application
        run: |
          if [[ "${{ runner.retry_count }}" -lt "${{ matrix.retry }}" ]]; then
            # Deployment command
            aws s3 sync ./dist s3://my-bucket
          else
            echo "Deployment failed after ${matrix.retry} retries"
            exit 1
          fi
