name: Example Workflow with Max Retry

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Retry automation reset
        uses: gabrielsev/rerun-workflow@v2
        with:
          # Configure the retries (number of times to retry if it fails)
          retries: 3
          # The delay between retries in seconds
          delay: 5

      - name: Run job with retry logic
        run: |
         set -e
         set -x
         hostname
