name: Example Workflow with Max Retry

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run job with retry logic
        uses: nick-fields/retry@v1
        with:
          # Configure the number of retry attempts
          retries: 3
          # Configure the delay between retries in seconds
          delay: 10
        run: |
         set -e
         set -x
         hostname
