jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-attempts: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run potentially failing task
        run: |
          # Your commands here
          echo "Running a task that might fail"
          # Simulating a potential failure
          exit $(( $RANDOM % 2 ))
