name: Example Workflow with Max Retry

on: [push]

jobs:
  retry_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run task with retry logic
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: |
            echo "Current attempt number: $ATTEMPT_NUMBER"
            set -e 
            set -x
            hostname1
      
      - name: Run if previous step succeeded
        if: success()
        run: echo "The task succeeded!"
      
      - name: Run if all attempts failed
        if: failure()
        run: echo "The task failed after all retry attempts"

      - name: Debug information
        if: always()
        run: |
          echo "Workflow completed"
          echo "Job status: ${{ job.status }}"
