name: Example Workflow with Max Retry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests with Retry Logic
        id: run_tests
        run: |
          MAX_RETRIES=3
          SUCCESS=0
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i of $MAX_RETRIES"
            if npm test; then
              echo "Tests passed on attempt $i"
              SUCCESS=1
              break
            else
              echo "Tests failed on attempt $i"
            fi
          done

          if [ $SUCCESS -ne 1 ]; then
            echo "Max retries reached. Failing the job."
            exit 1
          fi
