name: Example Workflow with Max Retry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests with Retry Logic
        id: run_tests
        env:
          RETRY_COUNT: 0
          MAX_RETRIES: 3
        run: |
          for i in $(seq 1 ${{ env.MAX_RETRIES }}); do
            echo "Attempt $i of ${{ env.MAX_RETRIES }}"
            if npm test; then
              echo "Tests passed on attempt $i"
              break
            else
              echo "Tests failed on attempt $i"
              export RETRY_COUNT=$i
            fi
          done
        continue-on-error: true

      - name: Fail if Max Retries Exceeded
        if: steps.run_tests.outcome == 'failure' && env.RETRY_COUNT == env.MAX_RETRIES
        run: |
          echo "Max retries reached. Failing the job."
          exit 1
