name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check job status with retry
        run: |
          MAX_RETRIES=3
          RETRY_COUNT=0
          SUCCESS=false

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            if [ "${{ job.status }}" == "success" ]; then
              echo "Job succeeded"
              SUCCESS=true
              break
            else
              echo "Job failed. Attempt $((RETRY_COUNT+1)) of $MAX_RETRIES."
              RETRY_COUNT=$((RETRY_COUNT+1))
              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                echo "Retrying..."
              fi
            fi
          done

          if [ "$SUCCESS" != "true" ]; then
            echo "Max retries reached. Job failed."
            exit 1
          fi
